### ISSUE TITLE
Add a CSV delimiter parameter to GetUse.jar or surround ENDPOINT with double quotes

### ISSUE THREAD

**Issue by pla1** [calix-hels/FA-Use-client#1]
We use commas in the the E7 subscriber ID field. Please add an input parameter to the GetUser.jar to specify the CSV delimiter.

`--delimiter |`

If adding a delimiter parameter is not possible, please surround the ENDPOINT data with double quotes. For example:

`05/25/2015 00:00:00,"E7-SCNX_E7_01-1-1-4-18-8-1-8431524277,8431501000-2306_Front_St",4761116700.00,265659460.00,567616.31,42883.38,3542238.80,390521.25`

**Comment by calix-hels** [comment]
Hi Patrick - 

Just a note that this request is being picked up by engineering.  This ticket will be updated as soon as the change is made.

-henning
(FAA-1809)

**Comment by queenaqian** [comment]
Hi Patrick, 

We've updated a new build supporting delimiter parameter under branch R2.1.7. You can download and have a try. Any question, please leave comments or contact us.

Thanks,
Qin

**Comment by pla1** [comment]
New `--delimiter` parameter works. :thumbsup:

**Comment by queenaqian** [comment]
Great. Thanks. Then I close this ticket. :)

Qin

**Comment by pla1** [comment]
The `--delimiter` parameter stopped working November 8, 2017. I haven't made any changes. Did something change on the server side? Can we get this working again?
